# Generated by Django 2.2.3 on 2019-09-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(max_length=100)),
                ('snr', models.DecimalField(decimal_places=4, max_digits=6)),
                ('data', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-received'],
            },
        ),
    ]
