# Generated by Django 2.2.3 on 2019-08-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('snr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
