# Generated by Django 2.2.3 on 2019-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigfoxcallbacks', '0002_auto_20190827_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='snr',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
